import Head from 'next/head'
import Layout from "@/components/Layout"
import Image from 'next/image';
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from '@/components/TransitionEffect';
import Swipe from '../components/swipe'

export default function Home() {
  return (
    <>
 
      
      <Head>
        <title>Fadil</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'> 
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className="flex items-center justify-between w-full lg:flex-col">
          <div className='relative w-1/2 md:w-full' style={{ top: '-100px' }}>
  <Image src={profilePic} alt="Fadil" className='pt-1 w-full h-auto lg:hidden md:inline-block md:w-full'
    priority
    sizes="(max-width:768px) 100vw, 
    (max-width:1200px)50vw,
    50vw"
  />
</div>
            <div className='w-1/2 h-1/2 flex flex-col items-center self-center lg:w-full lg:text-center  relative ' style={{ top: '-100px' }}>
             
              <AnimatedText text="Data Virtuoso: Converting Data Chaos into Clarity" className='!text-6xl !text-left
              xl:!text-5xl lg:!text-center lg:!text=6xl md:!text-5xl sm:!text-3xl dark:text-purple
              ' />
              
                       <div className="w-80 h-24 bg-black-500 rounded-full text-cyan-300 flex items-center  ">
                <div className="text-4xl font-bold">
                  <Swipe />
                </div>
              </div>






              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
              As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="/dummy.pdf" target={"_blank"}
                  className='flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark 
                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                hover:dark:border-light md:p-2 md:px-4 md:text base'
                  download={true}
                >Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link href="fadilmohammed208@gmail.com" target={"_blank"}
                className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base '
                >Contact</Link>
              </div>
            </div>
          </div>
          
          
        </Layout>
        <HireMe />
        <div className=' right-1 bottom-4  inline-block w-24 md:hidden'>
          <Image src={lightBulb} alt="Fadil" className='w-full h-auto' />
        </div>
        
      </main>

    </>
  )
}